AllCops:
  TargetRubyVersion: 2.5
  CacheRootDirectory: '/tmp/skittlize-rubocop-cache'

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: "comma"

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: "comma"
