---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: Run checks

    strategy:
      matrix:
        ruby_version:
          - 2.4
          - 2.5
          - 2.6
          - 2.7
          - 3.0

    runs-on: 'ubuntu-18.04'
    steps:
      - uses: actions/checkout@v2
      - name: Install ruby version ${{ env.ruby_version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true

      - name: RSpec
        run: |
          bundle exec rake spec

